### ISSUE TITLE
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?

### ISSUE THREAD

**Issue by quincarter** [edbizarro/gitlab-ci-pipeline-php#10]
Runner is failing when trying to open a lock file because it says I do not have root permissions?

```
Running with gitlab-runner 10.0.0-rc.1 (6331f360)
  on docker-auto-scale (4e4528ca)
Using Docker executor with image edbizarro/gitlab-ci-pipeline-php:7.0 ...
Using docker image sha256:ad2a804be38eddec66059b05a6ee5f596e3887ddddca62219c13d76ed306215e for predefined container...
Pulling docker image edbizarro/gitlab-ci-pipeline-php:7.0 ...
Using docker image edbizarro/gitlab-ci-pipeline-php:7.0 ID=sha256:8a485ae35d7ab8bed1c497efaeb1b88f44ccd938031c36a254a79b6d4348e974 for build container...
Running on runner-4e4528ca-project-3617016-concurrent-0 via runner-4e4528ca-machine-1506001341-3fda522f-digital-ocean-2gb...
Cloning repository...
Cloning into '/builds/myprojectnameisredacted'...
Checking out b888db38 as feature/featureBranch123...
Skipping Git submodules setup
Checking cache for feature/featureBranch123...
FATAL: file does not exist                         
Failed to extract cache
$ set -xe
$ apt-get install -y libxml2-dev nodejs npm
++ echo '$ apt-get install -y libxml2-dev nodejs npm'
++ apt-get install -y libxml2-dev nodejs npm
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
ERROR: Job failed: exit code 1
```

Any thoughts?

**Comment by edbizarro** [comment]
Hi @quincarter 

I'm changed the user in the images for security reasons, now all images run with the user `php`, so you need to run your commands in the debian images with sudo. `sudo apt get...`

**Comment by edbizarro** [comment]
btw. images already come with node, npm and yarn, u don't need to install these in your pipeline setup

**Comment by quincarter** [comment]
@edbizarro -- i am getting `bin/bash: line 55: sudo: command not found` in my runner. 

```
Checking out 399e85d8 as feature/mybranch123...
Skipping Git submodules setup
Checking cache for feature/mybranch123...
FATAL: file does not exist                         
Failed to extract cache
$ set -xe
$ sudo apt-get install -y libxml2-dev
++ echo '$ sudo apt-get install -y libxml2-dev'
++ sudo apt-get install -y libxml2-dev
/bin/bash: line 55: sudo: command not found
ERROR: Job failed: exit code 1
```

**Comment by edbizarro** [comment]
hi @quincarter 

Please try run again

**Comment by quincarter** [comment]
@edbizarro I am still getting the same error.

**Comment by antuspenskiy** [comment]
@edbizarro Hello!
We have error for same reason as above:

apk --update add php7-simplexml php7-fileinfo
ERROR: Unable to lock database: Permission denied
ERROR: Failed to open apk database: Permission denied

I think we need sudo package for alpine images )

**Comment by quincarter** [comment]
@antuspenskiy - yes i agree -- when in the docker config, it needs to have an `apt-get update && apt-get install sudo` somewhere. Then the runner user needs to be added to the `sudoers` group. @edbizarro --- this is what needs to happen if it is not already there.

**Comment by edbizarro** [comment]
hi @quincarter and @antuspenskiy 

I added the user php to the sodoers and added sudo package.

![screenshot from 2017-09-22 11-27-35](https://user-images.githubusercontent.com/84926/30749206-136ceb8c-9f89-11e7-82ac-97adab4663dd.png)


Sry for the problem.

**Comment by quincarter** [comment]
Okay it looks as though the 7.0 image is fixed, but the 7.1 image is not. 

edbizarro/gitlab-ci-pipeline-php:7.1-alpine

Can you verify that the sudo command has been added here? Thanks @edbizarro

**Comment by antuspenskiy** [comment]
hi @quincarter , edbizarro/gitlab-ci-pipeline-php:7.1-alpine image must be fixed with my PR #11 , and sudo package available in image.

**Comment by edbizarro** [comment]
as @antuspenskiy said, the 7.1 images already has sudo

![screenshot from 2017-09-22 13-49-05](https://user-images.githubusercontent.com/84926/30755404-d0a1398e-9f9c-11e7-81e0-9bd4ca02f56e.png)

**Comment by RamonSmit** [comment]
Same happened on my pipelines, also got this now: 
![image](https://user-images.githubusercontent.com/1906631/30760284-d0a345f2-9fd9-11e7-9560-42eac91559b4.png)

**Comment by edbizarro** [comment]
@RamonSmit using which tag did this happen?

**Comment by RamonSmit** [comment]
@edbizarro edbizarro/gitlab-ci-pipeline-php:7.1 ID=sha256:b9b39a103634cd882f726ff8aeac1a174f5d7c0ab18dc3386717e75d55bcba80

**Comment by edbizarro** [comment]
@RamonSmit try change your cache folder to ~/.composer/cache

**Comment by quincarter** [comment]
Yeah now our 7.1 image is messing up -----

```
Running with gitlab-ci-multi-runner 9.4.2 (6d06f2e)
Cloning repository...
Cloning into '/blah'...
Checking out c09e5c3f as feature/fixing-gitlab-ci...
Skipping Git submodules setup
Checking cache for feature/fixing-gitlab-ci...
Successfully extracted cache
/bin/bash: line 6: /somefile.tmp/CI_SERVER_TLS_CA_FILE: Permission denied
/bin/bash: line 6: /somefile.tmp/CI_SERVER_TLS_CA_FILE: Permission denied
ERROR: Job failed: error executing remote command: command terminated with non-zero exit code: Error executing in Docker Container: 1
```


And the first part of our `gitlab-ci.yml` looks like this --

```
image: edbizarro/gitlab-ci-pipeline-php:7.1-alpine

before_script:
  - set -xe
  - sudo apk add --update php7-simplexml

after_script:
  - sudo killall php

stages:
  - setup
  - test

setup:
  type: setup
  script:
    - composer install --quiet --no-interaction
    - sudo cp .env.testing .env
  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - vendor/
  artifacts:
    expire_in: 1 week
    paths:
      - vendor/
      - .env
```

**Comment by RamonSmit** [comment]
@edbizarro `~/.composer/cache` solved it for us! Thanks!

**Comment by edbizarro** [comment]
@quincarter please invalidate your cache, the older cache was generated with the image using the root user, and now the user is php

**Comment by edbizarro** [comment]
I'm closing this issue for now, if you have any problem please feel free to open another one.

Thanks
