### ISSUE TITLE
The removal of /usr/src/* breaks docker-php-ext-install on alpine build

### ISSUE THREAD

**Issue by StanvanHoorn** [edbizarro/gitlab-ci-pipeline-php#101]
Our pipelines fail because the sockets module can no longer be installed with docker-php-ext-install.

The error is `tar (child): /usr/src/php.tar.xz: Cannot open: No such file or directory`

This is because /usr/src/* is removed at cleanup for the alpine images.
https://github.com/edbizarro/gitlab-ci-pipeline-php/blob/1a456604e37c41cc2c07730f67b3c0cebf6bb630/php/scripts/alpine/cleanup.sh#L10

Is this intentional?

If so, is there a proper workaround?

Thanks

**Comment by edbizarro** [comment]
hi @StanvanHoorn 

Actually that's not intentional, i believe i can safe remove this dir from removal

**Comment by edbizarro** [comment]
fixed in https://github.com/edbizarro/gitlab-ci-pipeline-php/commit/2e59517d704a3f7b6bfad0447b8c3a5b9907f2f5

**Comment by StanvanHoorn** [comment]
Nice! Thanks for the quick fix.
