### ISSUE TITLE
PHP 8.0 request

### ISSUE THREAD

**Issue by bu4ak** [edbizarro/gitlab-ci-pipeline-php#111]
Thanks a lot for the amazing work bringing these images to the mass of us the Gitlab CI users. PHP 8.0 was released, and it would be great if we could have 8.0 builds as well.

**Comment by C0kkie** [comment]
That would be amazing yea

**Comment by edbizarro** [comment]
Hey folks, sorry for been in a hiatus for the last weeks, I'll dig into support PHP8 next week

Thanks!

**Comment by notbotman** [comment]
Awesome, excited to test 👍🏻

**Comment by Pezhvak** [comment]
@edbizarro I've just created a PR #112, would you take a look?

**Comment by thijskuilman** [comment]
Looking forward to PHP 8.0 support!

**Comment by edbizarro** [comment]
Images for PHP 8 available!
