### ISSUE TITLE
Support for Laravel Dusk?

### ISSUE THREAD

**Issue by FabioWidmer** [edbizarro/gitlab-ci-pipeline-php#12]
Is this great project already supporting Laravel Dusk tests?
If not it would be great if you can add Laravel Dusk. Thanks!

**Comment by edbizarro** [comment]
Hi @FabioWidmer 

I would say yes.

Looking in Dusk composer dependencies I see that relies on facebook/webdriver, which depends on curl and zip extensions, both included in the images.

**Comment by FabioWidmer** [comment]
@edbizarro Thank you for your reply. I will try Laravel Dusk in the future and if there is a problem I will let you know.
