### ISSUE TITLE
dont purge build-essential so makefiles can be used

### ISSUE THREAD

**Issue by rosenstrauch** [edbizarro/gitlab-ci-pipeline-php#18]
latest commit broke my builds which utilized a makefile

**Comment by edbizarro** [comment]
Hi @rosenstrauch,

The build essential package was removed due to images size, but u can install `make` in your pipeline config with apt-get install make or apk add --update make on Alpine version

**Comment by HMAZonderland** [comment]
I agree, keep it in, this happens;

```
$ sudo apt-get install build-essential --quiet --yes
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package build-essential
```

**Comment by edbizarro** [comment]
@HMAZonderland in your case u need to update the apt database with `apt-get update` before install
