### ISSUE TITLE
Soap extension

### ISSUE THREAD

**Issue by RamonSmit** [edbizarro/gitlab-ci-pipeline-php#2]
Hi There, 

How can I install the soap extension on this image? 
I'm getting the following error from Composer:
`hiddeco/transip v5.4 requires ext-soap * -> the requested PHP extension soap is missing from your system.`

Cheers,
Ramon 🍺

**Comment by edbizarro** [comment]
Hi @RamonSmit 

Which tag?

**Comment by RamonSmit** [comment]
Hi @edbizarro , 

I'm on `7.1`, `latest`

**Comment by edbizarro** [comment]
the soap extension was included, please update your local image (docker pull),  :)

**Comment by RamonSmit** [comment]
Hmm, maybe a idiotic question, but how do I pull on Gitlab CI?

**Comment by edbizarro** [comment]
the gitlab-runner pulls the newest version of the image before running the build

**Comment by edbizarro** [comment]
just retry the failed job and should work fine

**Comment by RamonSmit** [comment]
I shall try now 👍
