### ISSUE TITLE
Support for PHP 7.2

### ISSUE THREAD

**Issue by edbizarro** [edbizarro/gitlab-ci-pipeline-php#22]

**Comment by johnhout** [comment]
@edbizarro Any ETA on this?

**Comment by edbizarro** [comment]
@johnhout today! sry for delaying it

**Comment by johnhout** [comment]
@edbizarro NP Glad to see it show up :) Can I help you with anything?

**Comment by RamonSmit** [comment]
@edbizarro 
Did NPM change to v9 on purpose? We're having issues with our deployment stack at the moment. 

```
$ node -v
v9.4.0
```

`Using docker image edbizarro/gitlab-ci-pipeline-php:7.1 ID=sha256:a7c4b4e6ac1a178d769b15d89fb57cd21b4c800057c7ffaf4b485a64444bdc6a for build container...`

```
 Found bindings for the following environments:
          - Linux 64-bit with Node.js 8.x
```

**Comment by edbizarro** [comment]
hi @RamonSmit yes, the node package was updated to 9

What problem you're facing?

**Comment by RamonSmit** [comment]
@edbizarro Ah alright. 

We just invalidated our CI caches. That solved the problem looks like. 

We where facing this error:
```
ERROR in ../web/web.scss
    Module build failed: Error: Missing binding /builds/.../node_modules/node-sass/vendor/linux-x64-59/binding.node
    Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 9.x
    
    Found bindings for the following environments:
      - Linux 64-bit with Node.js 8.x
``` 

It was just a bit weird when the pipeline runs valid on a MR, and after the MR just breaks on every CI instance haha.
