### ISSUE TITLE
Python not found

### ISSUE THREAD

**Issue by viki53** [edbizarro/gitlab-ci-pipeline-php#24]
It's me again!

When installing the yarn dependencies, I get the following error:

```shell
Error: Can't find Python executable "python", you can set the PYTHON env variable.
```

Which causes `node-gyp` to crash, preventing `node-sass` to install.

So basically nothing gets installed and I can't build or test my app, at least with the `7.1-alpine` image

**Comment by edbizarro** [comment]
yeah, I'm including the python binaries in the next release today, the debian images already have it

**Comment by edbizarro** [comment]
python included
