### ISSUE TITLE
Imagick not working in 7.1

### ISSUE THREAD

**Issue by Numline1** [edbizarro/gitlab-ci-pipeline-php#27]
Hi,

with the recent release, ImageMagick/ext-imagick is broken when using 7.1. From the changes I've seen, it's not being installed at all. Was it removed intentionally or is this a bug?

Thanks :)

**Comment by Numline1** [comment]
@edbizarro I see you fixed this few hours ago, thank you :)

**Comment by edbizarro** [comment]
hi @Numline1, yes I forgot to mention here, sry.
