### ISSUE TITLE
Alpine images - xdebug

### ISSUE THREAD

**Issue by edbizarro** [edbizarro/gitlab-ci-pipeline-php#3]
Xdebug is not enabled on alpine based images

**Comment by juizmill** [comment]
I have the same problem.

**Comment by dextermb** [comment]
@edbizarro Did this get resolved? `xdebug` still isn't found for me:
```
php -d short_open_tag=off ./vendor/phpunit/phpunit/phpunit -v --coverage-text --colors=never --stderr
```

**Comment by edbizarro** [comment]
Hi @dextermb, yes all images have xdebug enabled, try pulling a updated version

**Comment by newsages** [comment]
php -d short_open_tag=off ./vendor/phpunit/phpunit/phpunit --coverage-text --colors=never --stderr
PHPUnit 7.5.13 by Sebastian Bergmann and contributors.

Error: No code coverage driver is available

**Comment by edbizarro** [comment]
hi @newsages 

Make sure you're using an updated version of the image (use docker pull to download latest build)

In case of persistent error please open another issue with details about your command and image version
