### ISSUE TITLE
Gyp error with Yarn

### ISSUE THREAD

**Issue by bedeMarkRadford** [edbizarro/gitlab-ci-pipeline-php#30]
I get this error when using node-sass with Yarn:

 `Error: /build/node_modules/node-sass: Command failed.  `

Which looks like it can't make:

`gyp ERR! stack Error: not found: make`

I found this when looking for the error:
https://github.com/DeviaVir/zenbot/issues/425

Suggesting we need build-essentials in the mix.
`sudo apt-get install build-essential git`

**Comment by edbizarro** [comment]
yes, you need to install the `build-essential` package to use `make` (or just install make and gcc)

**Comment by edbizarro** [comment]
hi, @bedeMarkRadford Did you get it to work?

**Comment by bedeMarkRadford** [comment]
I actually went around the problem and removed the dependency.
I'm not using Laravels Elixir which was the dependency causing the problems

**Comment by edbizarro** [comment]
Nice, if I can help you with something else feel free to reach me.

**Comment by GertjanRoke** [comment]
But why is the node version bumped to node 9 instead of 8? If you stead with node 8 there is no problem with node-sass that can not make a directory.

**Comment by edbizarro** [comment]
Because node 9 is the latest release

**Comment by GertjanRoke** [comment]
I know but not the latest LTS, maybe it is a good idea to only use the latest version of node with the latest version of php that your offering.
