### ISSUE TITLE
Composer cache permission denied

### ISSUE THREAD

**Issue by aletundo** [edbizarro/gitlab-ci-pipeline-php#32]
Hi @edbizarro,

From yesterday's evenining my pipelines started to fail to due this error:

```
composer install --prefer-dist --no-interaction --no-progress --no-suggest
Cannot create cache directory /home/php/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/php/.composer/cache/files/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/php/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file

                              
  [ErrorException]            
  mkdir(): Permission denied  
```
I noticed that user and group of `/home/php/.composer` is `root:root`. I applied an hack before run `composer install` in order to set the correct user and group:
```
sudo chown -R php:php ~/.composer

```
I don't why the error starts to appear yestard, maybe due to a composer update?
Let me know if you also faced this issue.

Cheers,

Alessandro

**Comment by edbizarro** [comment]
Hi @aletundo 

Tks! Yes, I made a mistake and broke these permissions, I already push a patch for that, sry for the trouble.

As soon as [the pipeline](https://gitlab.com/edbizarro/gitlab-ci-pipeline-php/pipelines/18970635) passes the image will be available

**Comment by aletundo** [comment]
@edbizarro thanks for your fast reply!

I will test your new image asap and I will give you feedback in order to set the issue fixed.

Cheers,

Alessandro

**Comment by aletundo** [comment]
Hi @edbizarro,

I tried the new image without my fix and it works as expected. You can mark this issue as fixed!

Cheers,

Alessandro

**Comment by ghost** [comment]
@edbizarro , isso deveria estar funcionando? Esse erro está aparecendo em meus builds.

**Comment by edbizarro** [comment]
oi @ricardovigatti sim, já foi corrigido.

Qual erro está acontecendo e qual versão da imagem?

**Comment by ghost** [comment]
Estou usando o Jenkins.

Testei:
 - edbizarro/gitlab-ci-pipeline-php:7.1
 - edbizarro/gitlab-ci-pipeline-php:7.2

Meu comando de build é apenas:
```
composer -V
```

A mensagem:

```
+ composer -V

Cannot create cache directory /home/php/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache

Cannot create cache directory /home/php/.composer/cache/files/, or directory is not writable. Proceeding without cache
```

**Comment by edbizarro** [comment]
você utiliza o cache do jenkins? Já tentou limpar o cache, caso vc cacheie a pasta do composer, isso acontece as vezes no gitlab quando usa o cache, invalidar o cache costuma resolver o problema no rebuild

**Comment by ghost** [comment]
Não me parece ser algo do Jenkins, afinal, o comando "composer -V" e a mensagem acontecem dentro do container. Ou será que eu estou confundindo as coisas?

**Comment by edbizarro** [comment]
nunca utilizei o jenkings então não sei dizer ao certo como funciona o sistema de cache dele, porém é explícito, se você não configurou o cache provavelmente ele não deve fazer sozinho da pasta ~/.composer pra ela ficar disponível entre builds.

Consegue testar com as variantes `alpine` pra ver se o erro acontece tb?

Não recomendo o uso em produção pois todas as imagens vem com quase todas as extensions PHP instaladas, provavelmente você não precisa delas, o que vai deixar sua imagem final bem maior do que o necessário, e também o xdebug, que acaba afetando drásticamente a performance da aplicação.

**Comment by ghost** [comment]
Acho que já testei com alpine tb, mas vou conferir. Também vou procurar saber sobre o cache. Estou começando agora com o Docker, então pode ser mesmo algum vacilo meu.

Você sabe dizer se essas imagens são boas para serem utilizadas em ambiente de produção?

**Comment by edbizarro** [comment]
Eu tinha editado a mensagem acima, vou replicar aqui com a resposta

Não recomendo o uso em produção pois todas as imagens vem com quase todas as extensions PHP instaladas, provavelmente você não precisa delas, o que vai deixar sua imagem final bem maior do que o necessário, e também o xdebug, que acaba afetando drásticamente a performance da aplicação.

**Comment by ghost** [comment]
Entendi, obrigado!
