### ISSUE TITLE
Node Version

### ISSUE THREAD

**Issue by lucidlemon** [edbizarro/gitlab-ci-pipeline-php#34]
Hi there,

In your readme you state that all versions of the image come with node 9 installed.
Whe I run my pipeline with `edbizarro/gitlab-ci-pipeline-php:7.2-alpine`, which according to `docker images -a` is `edbizarro/gitlab-ci-pipeline-php   7.2-alpine           c83c606e6603        4 days ago          441MB`, and I run this..

```
$ node -v
v7.10.1
```

I get a very old version 7.10.1 in return (july 2017). Am I missing something here?

by the way yarn doesn't even upgrade itself:

```
$ sudo npm install -g yarn
npm WARN npm npm does not support Node.js v7.10.1
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10.
npm WARN npm You can find the latest version at https://nodejs.org/
```

**Comment by RSchwan** [comment]
I'm also using `edbizarro/gitlab-ci-pipeline-php:7.2-alpine ` and since some days I have trouble with my wepack builds. It looks like yarn isn't properly downloading packages. The current version is so or so way outdated:
```
$ yarn install
yarn install v0.23.3
[1/4] Resolving packages...
warning Integrity check: Patterns don't match
[2/4] Fetching packages...
warning fsevents@1.2.0: The platform "linux" is incompatible with this module.
info "fsevents@1.2.0" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 54.73s.
$ yarn run production
yarn run v0.23.3
$ cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js 
 ERROR  Failed to compile with 3 errors4:42:46 PM

 error  in ./resources/assets/sass/app.scss

Module build failed: Error: ENOENT: no such file or directory, scandir '/builds/secret/project/node_modules/node-sass/vendor'
```

**Comment by edbizarro** [comment]
hi @lucidlemon, thanks to point it out, currently alpine versions have a wrong node version indeed, I'll fix this tonight, a temporary workaround is to use the debian version, which is `edbizarro/gitlab-ci-pipeline-php:7.2`

**Comment by lucidlemon** [comment]
that would be great :)

switching to debian is not always too easy, would require changing a lot in my scripting (a few apk vs apt-get things etc)

**Comment by edbizarro** [comment]
Alpine images now have the latest node version

**Comment by josefglatz** [comment]
@edbizarro I ran into troubles after switching to the latest node version. Do you think it makes sense, to also tag images on docker hub which has specific node versions?

**Comment by edbizarro** [comment]
@josefglatz It's possible, I'll tag a LTS version

**Comment by edbizarro** [comment]
All `alpine` images now have a LTS version with node LTS

`7.2-alpine-lts`, `alpine-lts`

`7.1-alpine-lts`

`7.0-alpine-lts`

**Comment by edbizarro** [comment]
I'm closing this issue since LTS versions are available.
