### ISSUE TITLE
Reading Exif data is not supported by this PHP installation

### ISSUE THREAD

**Issue by easteregg** [edbizarro/gitlab-ci-pipeline-php#4]
Hi, 

I have failed running test in laravel projects requiring `intervention`, after some digging, found out that using some of the intervention functions internally require `exif` to be installed. 
see [intervention doc for orientate function](http://image.intervention.io/api/orientate). 

I was wondering if it is possible to add exif extension to default php extensions?

> exact error in build: 
```
Intervention\Image\Exception\NotSupportedException: Reading Exif data is not supported by this PHP installation. in /builds/[..]/[..]/vendor/intervention/image/src/Intervention/Image/Commands/ExifCommand.php:19
```

**Comment by edbizarro** [comment]
Hi @easteregg 

Tks for using this project, I'm including the extension asap

What tag are you using?

**Comment by easteregg** [comment]
@edbizarro come on man, thank you for making awesome stuff. I'm just a user. 
using `7.0` now.

**Comment by edbizarro** [comment]
done!

**Comment by easteregg** [comment]
Impressive work, perfect. I'm closing this now.

**Comment by timacdonald** [comment]
Hey! Trying this out but I'm also getting this error. Currently using...

```
image: edbizarro/gitlab-ci-pipeline-php:7.1
```

Error is:
```
Intervention\Image\Exception\NotSupportedException: Reading Exif data is not supported by this PHP installation.
```

Any ideas on this one? I'm just using the basic: https://github.com/edbizarro/gitlab-ci-pipeline-php#simple-gitlab-ciyml-using-mysql-service

Thanks!

**Comment by edbizarro** [comment]
Hi @timacdonald 

In fact with the new build I forgot to include the exif extension, sry, I'm including now. When the build passes (~20, 30 minutes from now) the extension will be available

**Comment by timacdonald** [comment]
@edbizarro haha - awesome - thought I was going crazy - thanks so much for fixing that up and providing this - it looks very handy!
