### ISSUE TITLE
Question: user/group permissions on checked out files/folder

### ISSUE THREAD

**Issue by josefglatz** [edbizarro/gitlab-ci-pipeline-php#40]
is there any known/correct solution with GitLab CI and edbizaro/gitlab-ci-pipeline-php to make checked out files editable by the containers user `php`?

We have actually the problem, that a gulp script (node) can't edit/override an existing file which was checked out from VCS.

The checked out files are rw-rw-rw- for every group. Owner is: root:root.

Should I only run a chown like `cd $CI_PROJECT_DIR && chown -R :aGroupWhichUserPhpBelongsTo` ?

**Comment by edbizarro** [comment]
Hi @josefglatz your yarn/npm install commands are running with sudo? Maybe this is the problem.

Are you running those commands inside a Gitlab/CI Pipeline or local with docker run?

**Comment by edbizarro** [comment]
hi @josefglatz did you get it to work?

**Comment by josefglatz** [comment]
hi, seems so. But this works in the last couple of month!
