### ISSUE TITLE
Question: Method to use Laravel Dusk

### ISSUE THREAD

**Issue by littpi-zz** [edbizarro/gitlab-ci-pipeline-php#41]
Hello.

I am trying to make use of Laravel Dusk and I am facing the following problem.

```
$ php artisan dusk
Laravel development server started: <http://127.0.0.1:8000>
Warning: TTY mode requires /dev/tty to be read/writable.
PHPUnit 7.1.5 by Sebastian Bergmann and contributors.

EEEEEEEEEEEEEEEEEEEEEEEEEEEE                                      28 / 28 (100%)

Time: 8.38 seconds, Memory: 16.00MB

There were 28 errors:

1) Tests\Browser\AdminPanel\AuthorityTest::testGuestLogin
Facebook\WebDriver\Exception\WebDriverCurlException: Curl error thrown for http POST to /session with params: {"desiredCapabilities":{"browserName":"chrome","platform":"ANY","chromeOptions":{"binary":"","args":["--disable-gpu","--headless"]}}}
```

I have installed Google Chrome in the machine and I don't know the exact solution to solve this error... Should I set .env.dusk.local instead of using the variables in the .gitlab-ci.yml? Or should I set the variables inside the YAML file? Hope I can get some suggestions in here.

**Comment by edbizarro** [comment]
hi @littpi did you solve this issue?

**Comment by littpi-zz** [comment]
@edbizarro Not yet... I have just abandoned it for a while as I run the test through local but not the runner.

Do you have any methods to achieve this?

**Comment by se1exin** [comment]
Just chiming in, I gave this a go and got it working (for the most part - see the bottom of the post..) with the following:

Based off `https://gist.github.com/varyonic/dea40abcf3dd891d204ef235c6e8dd79`

`.gitlab-ci.yml`:

```
variables:
  # Other variables...
  CHROMEDRIVER_VERSION: "2.19"
  CHROMEDRIVER_DIR: "/chromedriver"

test:
   # .. other config options
  before_script:
    # .. other install commands

    # Google Chrome / Chromedriver dependencies
    - sudo apt-get install unzip xvfb libxi6 libgconf-2-4 libnss3 wget -yqq

    # Install Google Chrome so Chromedriver works
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
    - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
    - sudo apt-get update -yqq
    - sudo apt-get install -y google-chrome-stable

    # Install Chromedriver
    - sudo mkdir $CHROMEDRIVER_DIR
    - sudo wget -q --continue -P $CHROMEDRIVER_DIR "http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
    - sudo unzip $CHROMEDRIVER_DIR/chromedriver* -d $CHROMEDRIVER_DIR
    - sudo chmod -R 777 $CHROMEDRIVER_DIR

  script:
    # .. Other commands, such as composer install etc

    # Start xvfb so that Chrome actually works..
    - sudo Xvfb -ac :0 -screen 0 1280x100000x16 &
    - $CHROMEDRIVER_DIR/chromedriver &
    # Note my .env file has the entry APP_URL=http://127.0.0.1:8000 so as to map dusk to artisan serve
    - php artisan serve &
    # Give things a few seconds to start (hence the sleep 5)
    - sleep 5 && php vendor/bin/phpunit -v --coverage-text --colors=never --stderr tests
```

Lastly, I still occasionally get the error `Facebook\WebDriver\Exception\NoSuchDriverException: no such session`, but am currently mitigating with the answers from https://github.com/laravel/dusk/issues/105. Specifically by adding `sleep(5)` at the start of my tests, and only having 1 test per file. Note that the `sleep 5` command is also needed as part of the final `sleep 5 && php vendor/bin/phpunit -v --coverage-text --colors=never --stderr tests` above to make CI wait for chromedriver to start.

**Comment by littpi-zz** [comment]
Sorry dude, I am so busy that I just read your reply now. I will try to test it again and give the feedback within a few days.

**Comment by edbizarro** [comment]
see https://github.com/edbizarro/gitlab-ci-pipeline-php/issues/48
