### ISSUE TITLE
Laravel Dusk on gitlab-ci-pipeline-php

### ISSUE THREAD

**Issue by rennokki** [edbizarro/gitlab-ci-pipeline-php#48]
So, after a few months i wanted to implement Dusk with gitlab-ci-pipeline-php, i have finally acheived the configuration for Dusk. Note that i use: `edbizarro/gitlab-ci-pipeline-php:7.2` in tests (or any debian-based, non-php-fpm based image; this does not work on alpine, but i think it can be easily transcripted into alpine commands).

The thing is that i need to run this as `before_script`:
```yaml
before_script:
    - sudo apt-get update -y
    - sudo apt-get install unzip xvfb libxi6 libgconf-2-4 libnss3 wget -yqq
    # Install Google Chrome
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
    - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
    - sudo apt-get update -yqq
    - sudo apt-get install -y google-chrome-stable
```

And this is the part in the `script` that actually fires the chromedriver & tests:
```yaml
script:
    - php artisan serve &
    - ./vendor/laravel/dusk/bin/chromedriver-linux --port=9515 &
    - sleep 5
    - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml
    - php artisan dusk
```

However, the `before_script` can be easily be imported into the main image, so the tests won't take ~2 extra mins every build. Might come with a PR on this.

**Comment by edbizarro** [comment]
Hi @rennokki thanks for the suggestion!

I'm thinking of creating a tag for laravel projects that also include tools for dusk, that way the main tags do not get bloated

**Comment by rennokki** [comment]
@edbizarro So, it seems like i've treated this problem with a new bash file (like `node.sh` works), and i hope that's good. I'm not sure if i have to create a MR in Gitlab, but i think i'll do it to run the tests.

I've referenced https://github.com/edbizarro/gitlab-ci-pipeline-php/pull/51

On Gitlab it is this one: https://gitlab.com/edbizarro/gitlab-ci-pipeline-php/merge_requests/1 (feel free to close which one which; i'm not sure where to contribute to)

**Comment by edbizarro** [comment]
resolved https://github.com/edbizarro/gitlab-ci-pipeline-php/commit/5a9bbab22cf69497bfe3226dd6230500c4c09c4f

Thanks for the effort/inspiration and script file

**Comment by rennokki** [comment]
Finally i can cut off my build length :D Great job!!!1!
