### ISSUE TITLE
Node v8 support possible?

### ISSUE THREAD

**Issue by josefglatz** [edbizarro/gitlab-ci-pipeline-php#49]
Hey,

I'm wondering if it is possible to add also support node v8. Some of my projects uses node v8 and the build fail with node v10.

What do you think about it?

**Comment by edbizarro** [comment]
hi @josefglatz 

Since nodejs is not the aim of this project I'm afraid that maintain v8 (or other than current and LTS) is hard and off scope

**Comment by edbizarro** [comment]
But, you can easily write a script line that installs v8 in your pipeline

**Comment by josefglatz** [comment]
Thank you for ya feedback! 👍🏻
