### ISSUE TITLE
7.x-alpine-lts installs outdated version of Node.js (10.0.0)

### ISSUE THREAD

**Issue by f000** [edbizarro/gitlab-ci-pipeline-php#52]
All 7.x-alpine-lts images of gitlab-ci-pipeline-php install outdated version of Node.js LTS - version 10.0.0 but the current version of LTS is 10.15.1.

    ll@ntb:~/ci-test$ docker pull edbizarro/gitlab-ci-pipeline-php:7.1-alpine-lts
    7.1-alpine-lts: Pulling from edbizarro/gitlab-ci-pipeline-php
    81033e7c1d6a: Pull complete
    347280e4401e: Pull complete
    575b1e17046f: Pull complete
    b26c263d6f02: Pull complete
    7abf506b723b: Pull complete
    d2810cd6888e: Pull complete
    45135cb88bb2: Pull complete
    f727912d31a6: Pull complete
    aaa98808781d: Pull complete
    41493aa53708: Pull complete
    784d93510e97: Pull complete
    921d6ba296b3: Pull complete
    486ad5e22a06: Pull complete
    Digest: sha256:085fd4afba7c4a8a0e7e87556fa05e24f39a82b1bdead61ed1484988b5ae00b6
    Status: Downloaded newer image for edbizarro/gitlab-ci-pipeline-php:7.1-alpine-lts
    ll@ntb:~/ci-test$ docker run edbizarro/gitlab-ci-pipeline-php:7.1-alpine-lts node -v
    v10.0.0

    ll@ntb:~/ci-test$ docker run edbizarro/gitlab-ci-pipeline-php:7.2-alpine-lts bash
    Unable to find image 'edbizarro/gitlab-ci-pipeline-php:7.2-alpine-lts' locally
    7.2-alpine-lts: Pulling from edbizarro/gitlab-ci-pipeline-php
    605ce1bd3f31: Pull complete
    2f5aa494661d: Pull complete
    7963c90c835a: Pull complete
    a3f2a1640434: Pull complete
    937931eef522: Pull complete
    8499d1aeb03e: Pull complete
    537edaa69db5: Pull complete
    cf779c0e9c28: Pull complete
    643606afc134: Pull complete
    3cf77a8fdfd3: Pull complete
    c0f939f9c125: Pull complete
    167d84ce7538: Pull complete
    0cd2a70a7f37: Pull complete
    Digest: sha256:e1a97054eaf181a1c4ede8c30312aaf5e8399978781114f9668f8910bffcffbf
    Status: Downloaded newer image for edbizarro/gitlab-ci-pipeline-php:7.2-alpine-lts
    ll@ntb:~/ci-test$ docker run edbizarro/gitlab-ci-pipeline-php:7.2-alpine-lts node -v
    v10.0.0

    ll@ntb:~/ci-test$ docker pull edbizarro/gitlab-ci-pipeline-php:7.3-alpine-lts
    7.3-alpine-lts: Pulling from edbizarro/gitlab-ci-pipeline-php
    4fe2ade4980c: Pull complete
    5cf60c0c0763: Pull complete
    468219aa4689: Pull complete
    4a8b1a3b9e51: Pull complete
    c1d6c3f67455: Pull complete
    507023f149c0: Pull complete
    7f39820bea78: Pull complete
    4cbb710e1311: Pull complete
    ddd42cd0d8c8: Pull complete
    1e92cc645786: Pull complete
    8a6b659b1b39: Pull complete
    5799faab8635: Pull complete
    ed03c6007620: Pull complete
    03d1228d749b: Pull complete
    Digest: sha256:dbb045cf93b6813a6168b532bede17d3be44187dce1863bab2f2a2ff2889f2e8
    Status: Downloaded newer image for edbizarro/gitlab-ci-pipeline-php:7.3-alpine-lts
    ll@ntb:~/ci-test$ docker run edbizarro/gitlab-ci-pipeline-php:7.3-alpine-lts node -v
    v10.0.0

**Comment by edbizarro** [comment]
Thanks @f000 

I'll take a look at this asap

**Comment by edbizarro** [comment]
Fixed
