### ISSUE TITLE
Revert to node 11

### ISSUE THREAD

**Issue by j3j5** [edbizarro/gitlab-ci-pipeline-php#60]
Hi, is there a way to revert the node version to 11? My builds are failing due to https://github.com/sass/node-sass/pull/2633, which is blocked and won't be merged till the people from node implement the NaN version.

Could you release a tag with node 11, at least till node-sass is fixed? Any other suggestions?

Thanks.

**Comment by edbizarro** [comment]
Sure!, node-saas package is very problematic indeed.

I'll keep an eye on that issue to update to node 12 only after they fix the problem.

In the meantime. the alpine images have a `lts` version, if you're using it, just append `-lts` in the image name until the build of v11 finished.

**Comment by j3j5** [comment]
Thank you very much, unfortunately I'm not using alpine atm but, since you mention it I'm going to try if migrating the image for our builds isn't too problematic. I can't remember why we weren't using it in the first place but is worth a try.

Obrigado pelo seu ótimo trabalho.

**Comment by edbizarro** [comment]
All images (except lts) are changed back to Node v11

**Comment by edbizarro** [comment]
Version [node-saas/v4.12.0](https://github.com/sass/node-sass/releases/tag/v4.12.0) was released with support for node v12.

I'm going to close this issue and update all images to v12 again.

**Comment by j3j5** [comment]
Great, thanks for the quick action!
