### ISSUE TITLE
How to enable sockets extension

### ISSUE THREAD

**Issue by phikhi** [edbizarro/gitlab-ci-pipeline-php#63]
I am trying to enable the php `sockets` extension.

So I tried to run :
`docker-php-ext-install sockets`

`docker-php-ext-enable sockets`

and I get that error : 
```
$ docker-php-ext-install sockets
mkdir: cannot create directory '/usr/src/php': Permission denied
```

Do somebody have any idea how to make it work ?

**Comment by edbizarro** [comment]
Try with sudo -E

Alpine:

`sudo apk add --no-cache autoconf`
`sudo -E docker-php-ext-install sockets`

Debian:

```
sudo apt-get update
sudo apt-get install autoconf -y
sudo -E docker-php-ext-install sockets
```

**Comment by phikhi** [comment]
@edbizarro thanks ! it works perfectly !
