### ISSUE TITLE
[FEATURE] Multiples databases

### ISSUE THREAD

**Issue by abkrim** [edbizarro/gitlab-ci-pipeline-php#65]
Hello

I have tried several ways to implement the use of more than one BD in the mysql image.

The official image of Mysql does not have more than one BD but I have seen some tips that work but I do not get it with your utility and I think it is because I do not know well docker composer and the other means of generating or deploying dockers.

If you look in the [Mysql code  ](https://github.com/docker-library/mysql/blob/333935aa6612376d58737a8cab0e3f5df370585a/8.0/docker-entrypoint.sh#L197)there is a directory that runs, but I am not able.

I've reviewed things like [this](https://github.com/abagayev/docker-bootstrap-collection/blob/master/mysql-few-databases/docker-compose.yml)  but I always get the same problem, and relative to what is a method different in my opinion and my little knowledge of docker.

I don't know if it's possible to implement it or simply if you can tell me how I can achieve that goal.

**Comment by abkrim** [comment]
After some investigation I see a method for this issue.

But I get erro because mysql client not installed in alpine version.

```bash
$ echo "CREATE DATABASE IF NOT EXISTS \`${DB_2}\`;" | mysql --user=root --password="MYSQL_ROOT_PASSWORD" --host=mysql
/bin/bash: line 94: mysql: command not found
```

```yaml
script:
    - echo ${DB_2_USER}
    - echo $hostname
    - echo "CREATE DATABASE IF NOT EXISTS \`${DB_2}\`;" | mysql --user=root --password="MYSQL_ROOT_PASSWORD" --host=mysql
    - echo "CREATE USER '${DB_2_USER}'@'%' IDENTIFIED BY '${DB_2_PASSWORD}';" | mysql --user=root --password="MYSQL_ROOT_PASSWORD" --host=mysql
    - echo "GRANT ALL ON ${DB_2}.* TO '${DB_2_USER}'@'%';" | mysql --user=root --password="MYSQL_ROOT_PASSWORD" --host=mysql
    - echo "FLUSH PRIVILEGES;" | mysql --user=root --password="MYSQL_ROOT_PASSWORD" --host=mysql
```

But if read your script `packages.sh` I see

```bash
 apk update \
&& apk --no-cache upgrade \
&& apk --no-cache add \
    g++ \
    gcc \
    git \
    grep \
    libc-dev \
    make \
    mariadb-client \
    openssh-client \
    openssl \
    python \
    rsync \
    sudo \
    zip
```

I'm lost. Why if installed mariadb-client mysql not found ?

**Comment by tenken** [comment]
I am able to create multiple databases without issue with a simple CI script in my pipelines first job. I have not encountered the issue you described.

I had to assure I have a `services` entry in my gitlab ci file so that my container could connect to a mysql instance.

**Comment by abkrim** [comment]
Well, the truth is that I was not able to do it as you indicate. I even looked for the mysql image documentation and saw that I had the problem that it is limited to a single database.

In the end choose another path. That the different connections in testing mode become the same database, but with a prefix.

Thank you anyway.

**Comment by edbizarro** [comment]
Closing this issue since it's related to gitlab ci itself
