### ISSUE TITLE
phpunit permission denied

### ISSUE THREAD

**Issue by C0kkie** [edbizarro/gitlab-ci-pipeline-php#70]
Hello,

i use the image edbizarro/gitlab-ci-pipeline-php:7.3 and i get the error

$ ./vendor/phpunit/phpunit/phpunit -v --coverage-text --colors=never --stderr
/bin/bash: line 105: ./vendor/phpunit/phpunit/phpunit: Permission denied

**Comment by C0kkie** [comment]
is it possible to add phpunit directly in the image?

**Comment by C0kkie** [comment]
no response at all?

**Comment by edbizarro** [comment]
Hi @C0kkie 

Are you running any command with sudo before the PHPUnit? Probably composer install? If is the case then any command after will need sudo too.

It could be possible to include PHPUnit by default, but I think most of the PHP projects already have PHPUnit in their dev-dependencies

**Comment by C0kkie** [comment]
Hey,

it looks like that

test:
  stage: test
  services:
    - mysql:5.7
  image: edbizarro/gitlab-ci-pipeline-php:7.3-alpine
  script:
    - yarn config set cache-folder .yarn
    - yarn install --pure-lockfile
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
    - cp .env.example .env
    - php artisan key:generate
    - php artisan migrate:refresh --seed
    - vendor/bin/phpunit

**Comment by edbizarro** [comment]
Weird, try to clear the Gitlab CI cache and run again. 

![Pipelines · Power Data Hub   saas   data   maestro · GitLab](https://user-images.githubusercontent.com/84926/68479966-5a8bce00-0212-11ea-9f3e-c28c9e22c978.png)

**Comment by C0kkie** [comment]
I already did that^^

**Comment by Ayesh** [comment]
This can happen when you have the `vendor/bin` directory committed to Git from a file system that does not support permissions (Read: Windows). You can call `rm -Rf vendor` before `composer install`, which should fix the permissions by itself.

**Comment by C0kkie** [comment]
oh yea....i am dumb, sorry. It works now with that @Ayesh
