### ISSUE TITLE
mkdtemp: private socket dir: Permission denied

### ISSUE THREAD

**Issue by dahaupt** [edbizarro/gitlab-ci-pipeline-php#71]
Since the last update I get this error in my deployment script:
```bash
$ eval $(ssh-agent -s)
mkdtemp: private socket dir: Permission denied
$ [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
$ ssh-add <(echo "$SSH_PRIVATE_KEY")
Could not open a connection to your authentication agent.
```
It worked fine on the last pipeline 12 hours ago.

Executing `sudo chmod 1777 /tmp` resolves the issue (as found [here](https://github.com/babun/babun/issues/815)).

Thanks for your dedicated work!

**Comment by edbizarro** [comment]
Fixed!

**Comment by dahaupt** [comment]
@edbizarro Thanks a lot, it's working fine again!
