### ISSUE TITLE
Permissions for CI_PROJECT_DIR corrupt?

### ISSUE THREAD

**Issue by josefglatz** [edbizarro/gitlab-ci-pipeline-php#77]
Using the tag `7.2` my files in $CI_PROJECT_DIR have user/group set to `root`.

Is this a bug in one of the latest fixes for `7.2`? Actually I have to change via `chown -R php:php $CI_PROJECT_DIR`

Is this a known change or do I have to set it anywhere? I can't find a username option in `.gitlab-ci.yml`

**Comment by edbizarro** [comment]
Did you run any commands with sudo in your scripts? The `php` USER is set in the image so any commands should run with that user.

**Comment by josefglatz** [comment]
This is what I do.

I never use sudo or `sudo su`. Maybe it has something todo with my older GitLab version?

**Comment by edbizarro** [comment]
Maybe something related to https://github.com/edbizarro/gitlab-ci-pipeline-php/issues/70#issuecomment-552614073 ? File permissions from your dev machine commited to the repository

**Comment by edbizarro** [comment]
hi @josefglatz have you find the root of the problem?

thks

**Comment by josefglatz** [comment]
@edbizarro no, not until. I‘m investigating further

**Comment by josefglatz** [comment]
@edbizarro I checked https://github.com/edbizarro/gitlab-ci-pipeline-php/blob/52c07d01c894e47fad114cea8d786ec9305361d0/php/7.3/Dockerfile#L17

Does that mean, that the gitlab ci runner must run with the same user "php" on the host of the gitlab ci runner?

Actually the $CI_PROJECT_DIR has `root:root` permissions within GitLab CI when the CI checks the GIT repo out.

Do you have anything configured on your ci runner host. Any tipps?
