### ISSUE TITLE
Missing extension for Cassandra

### ISSUE THREAD

**Issue by erickskrauch** [edbizarro/gitlab-ci-pipeline-php#78]
16 days ago, my [pull](https://github.com/edbizarro/gitlab-ci-pipeline-php/pull/75) [request](https://github.com/edbizarro/gitlab-ci-pipeline-php/pull/76) to add the Cassandra extension was accepted. We integrated the updated image in our CI and everything was fine. But 5 days ago, some kind of automatic build for alpine led to a rollback of these changes, which caused us to fail CI.

I guess a system that automatically updates something in alpine images didn't get the latest changes from the repository?

P.S. debian-based images are not affected.

**Comment by edbizarro** [comment]
Weird, when I run ` docker run -it --rm edbizarro/gitlab-ci-pipeline-php:7.3 php -m` cassandra is listed as installed.

Are you using the latest build?

All images have extensions tests asserts before got pushed to the registry

**Comment by erickskrauch** [comment]
Please, try `docker run -it --rm edbizarro/gitlab-ci-pipeline-php:7.3-alpine php -m`. The problem exists only for alpine based images.

**Comment by edbizarro** [comment]
Oh, my mistake, I believe is caused by an error in gitlab's mirror, but now the extensions should be loaded.

**Comment by erickskrauch** [comment]
@edbizarro it happened again :(

**Comment by edbizarro** [comment]
@erickskrauch sry about that, I think everything is working as expected now.

I'll investigate to discover why this is happening from time to time

**Comment by erickskrauch** [comment]
@edbizarro, thank you.

Looks like you have some kind of periodic automatic build of alpine images, which takes the old version of the repository as a code base, without my changes.

**Comment by edbizarro** [comment]
yeah, that's exactly the problem, I've disabled the auto-build until I find a way to fix

**Comment by edbizarro** [comment]
merged https://github.com/edbizarro/gitlab-ci-pipeline-php/pull/83

Also, I've disabled the auto-build feature
