### ISSUE TITLE
Request for PHP 7.4 builds

### ISSUE THREAD

**Issue by Ayesh** [edbizarro/gitlab-ci-pipeline-php#80]
Hi Eduardo,
Thanks a lot for the amazing work bringing these images to the mass of us the Gitlab CI users. PHP 7.4 had its official release today, and it would be great if we could have 7.4 builds as well. 

Thanks a lot. Cheers.

**Comment by edbizarro** [comment]
I'm working on php 7.4 images right now :)

**Comment by Ayesh** [comment]
Awesome, thank you so much! I do see 7.4 images at docker hub, but they are 7.3 images (I'm not trying to sound pushy at all, just leaving the info for future Google users).

**Comment by nie7321** [comment]
Thanks @Ayesh, I just ran into that :-)

**Comment by Ayesh** [comment]
Hi @edbizarro - just pinging... I totally understand the festival season and the images are build on volunteer base and not to push anything, but I was wondering if you had some time for the PHP 7.4 builds. 

Thanks a lot.

**Comment by chrisbjr** [comment]
Hi @edbizarro thanks for the great work. I see that you've been pushing to get PHP7.4 working - waiting patiently for this. Thanks a lot!

**Comment by Ayesh** [comment]
I pushed a [a new my own docker image](https://hub.docker.com/r/phpwatch/docker-php) that has PHP 7.4, xdebug, composer, mysql-client, npm, and yarn in it. It is not to take over this package of course, as I am sure @edbizarro will maintain this responsibility. I had a few CI setups that were failing and were in an emergency, so I rolled the image myself.

**Comment by edbizarro** [comment]
Sorry guys, I've been very busy in the last days on my full-time job and had some trouble to install and compile all extensions on 7.4 builds, the image itself is functional, but some extensions are failing to install. I appreciate any help with those builds.

Thanks.

**Comment by edbizarro** [comment]
`7.4` tag is now available, also `7`, `fpm` and `alpine` now points to 7.4 version.

PHP 7.1 reached [end of life](https://www.php.net/supported-versions.php) and no longer receive new updated.

Ping to @erickskrauch because cassandra extension is failing in all 7.4 builds and I don't know exactly why :/

**Comment by erickskrauch** [comment]
@edbizarro, I'll see what's in there tomorrow. Is there somewhere I can see the build logs or build it on my PC?

**Comment by edbizarro** [comment]
> @edbizarro, I'll see what's in there tomorrow. Is there somewhere I can see the build logs or build it on my PC?

Sure, https://gitlab.com/edbizarro/gitlab-ci-pipeline-php/pipelines/106710640
