### ISSUE TITLE
WebP support

### ISSUE THREAD

**Issue by INOVAdev-joost** [edbizarro/gitlab-ci-pipeline-php#90]
GD is loaded without WebP support:

`$ php -r 'var_dump(gd_info());'
00:02
Command line code:1:
array(13) {
  'GD Version' =>
  string(26) "bundled (2.1.0 compatible)"
  'FreeType Support' =>
  bool(true)
  'FreeType Linkage' =>
  string(13) "with freetype"
  'GIF Read Support' =>
  bool(true)
  'GIF Create Support' =>
  bool(true)
  'JPEG Support' =>
  bool(true)
  'PNG Support' =>
  bool(true)
  'WBMP Support' =>
  bool(true)
  'XPM Support' =>
  bool(false)
  'XBM Support' =>
  bool(true)
  'WebP Support' =>
  bool(false)
  'BMP Support' =>
  bool(true)
  'JIS-mapped Japanese Font Support' =>
  bool(false)
}`

Any hints on how to enable this option?
Tried reconfiguring GD with WebP enabled but I run into different problems and i'm not sure how to continue from here.

`- sudo docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-png-dir=/usr/include/ --with-jpeg-dir=/usr/include/ --with-webp-dir=/usr/include/`   
`- sudo docker-php-ext-install gd`   
`- docker-php-ext-enable gd`

**Comment by INOVAdev-joost** [comment]
I just cloned the repository and made some changes to support WebP and it's works for me:
`+    libwebp-dev \`

`-    && docker-php-ext-configure gd --with-freetype --with-jpeg \`
`+    && docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp \`

`-    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \`
`+    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ --with-webp-dir=/usr/include/ \`

[extensions.sh.txt](https://github.com/edbizarro/gitlab-ci-pipeline-php/files/4408371/extensions.sh.txt)

Any chance on adding this to your repository ?

**Comment by edbizarro** [comment]
hi @INOVAdev-joost would you mind make a PR with theses changes? thanks!
