### ISSUE TITLE
Support for ext-gmp

### ISSUE THREAD

**Issue by alexanderkraemer** [edbizarro/gitlab-ci-pipeline-php#91]
Would it be possible, to add support for the ext-gmp in the php7.*-fpm image?

**Comment by edbizarro** [comment]
hi @alexanderkraemer would you mind make a PR to add this extension? thanks!

**Comment by alexanderkraemer** [comment]
https://github.com/edbizarro/gitlab-ci-pipeline-php/pull/93

**Comment by edbizarro** [comment]
Thanks @alexanderkraemer !

All images are updated with the new extension.
