### ISSUE TITLE
npx: command not found

### ISSUE THREAD

**Issue by Daniel-Mendes** [edbizarro/gitlab-ci-pipeline-php#96]
How can I use npx in my pipeline to run `npx stylelint resources/sass/**/*.scss` ?

I have the error `/bin/bash: line 95: npx: command not found`

I try `npm install -g npx`   in before_script, but I got ` npm WARN checkPermissions Missing write access to /usr/lib`

Do I have to add npx to my package.json

PS: I use `image: edbizarro/gitlab-ci-pipeline-php:7.4-alpine`

**Comment by Daniel-Mendes** [comment]
Work around:

I installed npx as dev dependency

And in pipeline `node_modules/.bin/npx stylelint resources/sass/**/*.scss`

**Comment by edbizarro** [comment]
hi @Daniel-Mendes are you still facing this problem?

**Comment by Daniel-Mendes** [comment]
I don't remember, i need to try again.

**Comment by edbizarro** [comment]
ok, if still happen please open up another issue, thanks!
